### PR TITLE
fix: bypass initial page requests

### PR DESCRIPTION
**Pull request by valendres**
Recreating https://github.com/valendres/playwright-msw/pull/46 on behalf of @SetupCoding since the PR was automatically closed when deleting the target branch.

**TODO:**

- [x] add test case to reproduce the issue (🙏 @SetupCoding)
- [x] address the root cause

### CODE REVIEW

**Comment by valendres** [comment]
@SetupCoding, I finally got around to implementing this. Sorry for the delay!

I've added a `waitForPageLoad` boolean flag (defaults to `false`) that waits for the page to load before mocking API calls. When enabled, it allows `playwright-msw` to mirror the behaviour of `msw` when it is running in the browser, where the initial static resource requests will not be mocked because `msw` will have only been initialized until after page load.

A couple of things I'm uncertain about are:

1) should this be the default behavior? if so, will changing the behavior negatively impact those already using the library?
2) does `waitForPageLoad` make sense, or is there a better name?

**Comment by SetupCoding** [comment]
@valendres  thank you very much for taking the time! No need to apologize!

Yeah I do believe that it should be the default behavior and I think there is no impact on the people who are already using the library. 

Another test that should be added - to ensure that there is no impact - might consist of the following scenario:

- A frontend route `localhost:3000/list`  where a list of items is being fetched e.g. inside a `useEffect`.
- A backend route mocked with rest.get(`*/list`, ...)

Then for the test somethign along the lines of: 
```ts
test('should not mock initial page request', async ({
    page,
    worker,
  }) => {
    await worker.use(
      rest.get('*/list', (_, response, context) =>
        response(context.delay(250), context.status(200), context.json([1,2,3,4]))
      )
    );
    await page.goto('/list');

    // expect page to be loaded - e.g. some heading should be visible
    // expect items to be fetched and displayed successfully e.g. list is visible and has 4 items
  });
```

`waitForPageLoad` sound good to me. 
Maybe also something like: `startWorkerAfterPageLoad`, `passthroughPageLoadRequest`,.

Again: Huge thanks for taking the time!
I am based in Germany so sorry for replying so late :)

**Comment by valendres** [comment]
@SetupCoding making this the default behavior makes sense to me. I've updated the default config to reflect this.

> Another test that should be added - to ensure that there is no impact - might consist of the following scenario:
> 
> A frontend route `localhost:3000/list` where a list of items is being fetched e.g. inside a `useEffect`.
> A backend route mocked with rest.get(`*/list`, ...)
> ...

I think I might be misunderstanding something here, but I believe that's what the original test that you wrote does. It loads a frontend route `/search` and performs a `GET /api/search` to load search results. With `waitForPageLoad` set to true, it does not mock the initial page route as desired. Whereas, when `waitForPageLoad` is set to false, the initial page route will be mocked and the subsequent `GET /api/search` will not be performed. I have added a test for this second scenario.

**Comment by SetupCoding** [comment]
Well, the original test that I wrote only ensures that the page is being loaded and the initial page response is not overridden by the service worker.
With the second test I wanted to ensure the same and additionally test that any subsequent requests that happen (e.g. in a `useEffect`) when a component is mounted (as part of the initial load of the page) are correctly mocked.

**Comment by valendres** [comment]
image

> Well, the original test that I wrote only ensures that the page is being loaded and the initial page response is not overridden by the service worker.

@SetupCoding Woops, I don't know how I missed this. My bad! Thanks for clarifying what you meant. I've added some tests to make sure that subsequent API calls are still being mocked as expected.

**Comment by SetupCoding** [comment]
Perfect! :D

**Pull request merged**
